title: Refactoring by example
email: hello@refactoringbyexample.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://refactoringbyexample.com"
title: Refactoring by Example
tagline: Real life refactoring examples
description: Practical examples of refactoring in the wild
url: http://www.refactoringbyexample.com
paginate: 5
permalink: /:year/:month/:title/
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
exclude:
  - Gemfile
  - Gemfile.lock
